name = "fabricaborgbots"
main = "src/index.ts"
compatibility_date = "2026-06-25"

preview_urls = false

[vars]
AI_MODEL_NAME = "gemini-flash-lite-latest"
WORKER_HOST = "fabricaborgbots.marketceogjr.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "bot_factory_db"
database_id = "61a5d89a-19d2-4851-9f5b-3f088b729d0c"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
